### ISSUE TITLE
Error number 272

### ISSUE THREAD

**Issue by Heinerion** [Vektah/CodeGlance#100]
I just loaded a 322.130 chars, 9.099 lines JS-File (fork of fullcalendar.io), closed it (before the code Highlighting was done) and this failure occurred.
My Project consists of about 200 files, of which 8 have been opened before the error showed up.

This Problem never occured prior to this, so I don't know how to reproduce.

**Comment by Vektah** [comment]
There are limits in place now, codeglance wont try to render files larger than 1M.
