### ISSUE TITLE
Not able to scroll properly after expand and collapse all

### ISSUE THREAD

**Issue by ikrsh** [Vektah/CodeGlance#101]
After Code > Folding > Expand all/Collapse all in java class file it is not scrolling properly from mini map. I guess issue is, it is taking few more seconds to update the mini map with expanded or collapsed view of the code. I meant the process to update the mini map is slow such and/or also some other situations.

Software : Android Studio 1.5

**Comment by Vektah** [comment]
Fixed in 1.5.0
