### ISSUE TITLE
CodeGlance won't display in files with more than 400 lines

### ISSUE THREAD

**Issue by Joha92** [Vektah/CodeGlance#102]
After 1.4.3 update, CodeGlance won't display in files with more than 400 lines. Tried by reinstalling but it did not help.

IntelliJ IDEA Ultimate 15.0.1
Windows 10 Professional, x86_x64
Java 8 x64 1.8 Update 51

**Comment by Vektah** [comment]
It's the result of https://github.com/Vektah/CodeGlance/issues/62

20kb may be too small :-/ 

I'm tempted to leave it till I do some performance tweaks at which point 1mb should be fine, maybe this weekend...

**Comment by Joha92** [comment]
Is there a way that we could set the memory limit in plugin configuration? That would be neat.

Thanks for the fast response however. :)

**Comment by Vektah** [comment]
It is in the config, but I didn't add it to the UI because its only going to be set low for a little while.

you can find the config in `~/.IntelliJIdea15/config/options/CodeGlance.xml`

Here is an absurdly high limit:
```
<application>
  <component name="CodeGlance">
    <option name="maxFileSize" value="10240000" />
  </component>
</application>
```

**Comment by Joha92** [comment]
Thanks, will override it for now.

**Comment by jisuo** [comment]
Where is this config (CodeGlance.xml) for Phpstorm?

**Comment by Vektah** [comment]
It should be in a similar spot, If its not there go into settings -> CodeGlance and change one of the settings and hit apply.

**Comment by jisuo** [comment]
I searched the entire disk for CodeGlance.xml, didn't find it. Also in Phpstorm there are no settings for this plugin.

https://www.dropbox.com/s/on7pvchfemjan5g/Screenshot%202015-12-08%2010.29.38.png?dl=0

Using OS X as you can see.

**Comment by zeljic** [comment]
It's located at ~/.WebIde100/config/options/CodeGlance.xml
But you have to change default settings in IDE.
Go to Settings -> Other Settings -> CodeGlance 
Change color for example. Confirm. Restart IDE.
Check path, there should be config file.

**Comment by zeljic** [comment]
BTW. adding <option name="maxFileSize" value="10240000" /> works just fine

**Comment by jisuo** [comment]
For some reason my .WebIde100 folder only has a "restart" folder with other stuff. No config/options/CodeGlance.xml is created. I've tried to change multiple settings, press apply or ok. Disable plugin, enable it again. 

I'm gonna try to manually add the file...

Now it works for files with about 500 lines. I upped the number to 40960000 just to test and it still won't work on files with about 800 lines. Hmm...

**Comment by thanhmssl10** [comment]
I think i get same problem, someone help me fix this please? :D

![388lineerror](http://imgur.com/hgSEkcS.gif)

**Comment by thefabulousdev** [comment]
+1

**Comment by Vektah** [comment]
Will roll out a 1.4.4 release shortly.

**Comment by Amitdutta121** [comment]
Just make the option value from true to false. in CodeGlance.xml file located in AppData\Roaming\JetBrains\WebStorm2021.1\options\CodeGlance.xml

<application>
  <component name="CodeGlance">
    <option name="disabled" value="false" />
    <option name="width" value="140" />
  </component>
</application>
