### ISSUE TITLE
CodeGlance is just working in php code

### ISSUE THREAD

**Issue by sDenizhan** [Vektah/CodeGlance#103]
hi, 
codeglance is just working in php code. When I work with html + php code, codeglance isn't work!

**Comment by Vektah** [comment]
It should work fine, depending how large the HTML file is your probably hitting https://github.com/Vektah/CodeGlance/issues/102

**Comment by tntu** [comment]
Since version 1.4.3 it stopped working for JAVA files.
Works for XML, JSON, SH, HTML, INI, PY.

**Comment by tntu** [comment]
After seeing issue #102 I can confirm small JAVA files do work but not large ones where it is most helpful.
