### ISSUE TITLE
selection color does not take effect until phpstorm restart

### ISSUE THREAD

**Issue by simonmichael** [Vektah/CodeGlance#109]
Related to #28. After reconfiguring the selection color, you have to restart phpstorm to see the change - would be better if it happened immediately. If not, it should warn.

Thanks for the plugin!

**Comment by Vektah** [comment]
You don't need to restart, just make a change on the document. I cant find an event to listen to trigger the image regeneration, but it happens all the time.

Marking wontfix, as I dont have a solution.
