### ISSUE TITLE
idea 2016 cann't show

### ISSUE THREAD

**Issue by ranbest** [Vektah/CodeGlance#113]
this plugin can not show  in version  2016.1

**Comment by Vektah** [comment]
Is it giving an error or is it just disabled in the settings? I think something similar happened when the last big update happened... Check the settings->plugins->CodeGlance and in settings->CodeGlance

**Comment by ranbest** [comment]
@Vektah  no errors and tips, just doesn't display

**Comment by ranbest** [comment]
I fund  when I new install and user default config. the plugin can show. but when i use old config, the plugin can't show,  who know  how to setting ?
