### ISSUE TITLE
Minimap only highlights the last out of multiple selections

### ISSUE THREAD

**Issue by DMA57361** [Vektah/CodeGlance#115]
Just installed v1.4.4 of CodeGlance. I've noticed that if I select several different elements of the page (with ctrl-G, middle-click drag, multiple alt-clicks, etc) only the most recently selected area is highlighted in the minimap, rather than every selected area.

---

Note sure if it helps or matters, but I'm running on Mac OSX 10.10.5 (Yosemite) with the following version for RubyMine:

> RubyMine 2016.1
> Build #RM-145.597, built on March 30, 2016
> JRE: 1.8.0_40-release-b132 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by Vektah** [comment]
duplicate of https://github.com/Vektah/CodeGlance/issues/69
