### ISSUE TITLE
Highlight scrolls at different rate to mouse cursor

### ISSUE THREAD

**Issue by Bilge** [Vektah/CodeGlance#116]
If you drag a standard Windows scrollbar thumb tracker it moves at the same rate as the mouse cursor. That is, if you click on the tracker at position (10, 20), as the tracker is dragged around, it remains under the mouse cursor at the same position such that when you stop dragging the cursor it is still at (10, 20) over the tracker.

However, the highlighted area in the CodeGlance preview scrolls at a different rate to the mouse cursor. That is, if you click on the highlight at position (10, 20), as the highlight is dragged around, it moves out of sync with the mouse cursor because it travels at a different rate such that when you stop dragging the cursor is no longer at (10, 20) over the highlight.

For large files (~2000 lines) the mouse cursor may be moving faster than the CodeGlance highlighted area which means it may be impossible to scroll from the very top to the very bottom because the mouse cursor reaches the edge of the screen before the entire file has been scrolled using the preview area.

This is a very uncomfortable usability issue that should be fixed such that the highlighted portion moves at the same rate as the mouse cursor when dragged.

**Comment by Vektah** [comment]
Fixed in 1.5.0

**Comment by Bilge** [comment]
🌟 Awesome! Thanks so much @Vektah. 💃
