### ISSUE TITLE
CodeGlance not visible

### ISSUE THREAD

**Issue by EdwardBurns** [Vektah/CodeGlance#122]
I was dragging the CodeGlance area to make it smaller and I accidentally dragged it all the way to the edge. Now I can't get it back. It's so tiny that I can't grab it without grabbing the frame of the editor window. I use WebStorm. I've tried deactivating & uninstalling the plugin, restarting Webstorm, and it does not restore the layout. I'm on a Windows 10 computer. How do I restore CodeGlance to it's original width? Thanks.

**Comment by EdwardBurns** [comment]
Found the setting. 

Settings ==> Other Settings ==> Width: 1  changed to 30

**Comment by arenaq** [comment]
For me it was disabled in the setting that Edward mentioned. Might be somehow related to an update cause I never disabled the plugin myself.

**Comment by space11** [comment]
I also had go to Other Settings => CodeGlance and manually enable it (deselect Disable checkbox)
