### ISSUE TITLE
Not work on Android Studio 2.1.2

### ISSUE THREAD

**Issue by jaredwangcode** [Vektah/CodeGlance#123]
Android Studio 2.1.2
JRE:1.8.0.60-b27 x86_64
OS X EI Captain 10.11.5

Hi:
when I upgrade my Android Studio IDE to the newest Version,CodeGlance just not worked.I tried to reinstall it,But still not work.

**Comment by jaredwang** [comment]
when i update to android studio 2.2 ,everything just fine....thx

**Comment by jaredwangcode** [comment]
when i update to android studio 2.2 ,everything just fine....thx
