### ISSUE TITLE
Not working at all with 15.0.2

### ISSUE THREAD

**Issue by ruwanthalk** [Vektah/CodeGlance#131]
This is not working at all on the above version. It shows empty pane on the right side

**Comment by WhyEvenTry** [comment]
Just an FYI for the record, I have no issues running it in 2016.2.4.

**Comment by alexb1nary** [comment]
PhpStorm 2016.2.1, ubuntu 16.04: not working at all, just disappeared on one moment. Reinstall does not help.

**Comment by alexb1nary** [comment]
Lol! I closed map minimized it, until it is completely disappeared, and I could not find the way, how to make it visible again. Sorry for comment above.

**Comment by ruwanthalk** [comment]
Is this issue fixed ?

**Comment by Vektah** [comment]
It should be. Did you check the width isnt set to zero in Settings -> other -> Codeglance?
