### ISSUE TITLE
In latest WebStorm release candidate ... debug will hang because of CodeGlance, WebStorm dev confirmed...

### ISSUE THREAD

**Issue by born2net** [Vektah/CodeGlance#136]
In latest WebStorm release candidate ... debug will hang because of CodeGlance, WebStorm dev confirmed...

regards

Sean

**Comment by born2net** [comment]
I am doing some more testing on RC and will reply back on findings...
closing for now

**Comment by Vektah** [comment]
Closed due to lack of information. reopen if you have some details.
