### ISSUE TITLE
impossible to retrieve CodeGlance after collapsing it completely

### ISSUE THREAD

**Issue by JCLaHoot** [Vektah/CodeGlance#145]
I tried to make CodeGlance smaller, and then thought "hey! what happens if I keep dragging to the right and make it disappear altogether?" 

Turns out, you can't bring it back once you do that. 

I've tried disabling, re-enabling, uninstalling and re-installing the plugin, but I can't get it to come back :(

**Comment by Vektah** [comment]
In the settings there is a box for the width. I probably should set a minimum...

**Comment by JCLaHoot** [comment]
didn't even realize there was a settings box! thanks
