### ISSUE TITLE
There should be a way to toggle the display w/o disabling plugin

### ISSUE THREAD

**Issue by yehosef** [Vektah/CodeGlance#15]
First - Fantastic plugin - kudos!

It would be great to have a way to toggle the display of the mini-code without disabling the plugin (which requires restarting the IDE).  There are times when I'm browsing the code looking for something where the view is very helpful.  There are other times (eg debugging) where I don't need the view and it just takes up screen real-estate.  I would like to be able to easily enable and disable the view base on the need.

**Comment by thevoiceless** [comment]
For anyone else that stumbles upon this in the future:
- Preferences > Other Settings > CodeGlance has a checkbox to enable/disable it
- Keyboard shortcut for toggling is under Keymap > Plug-ins > CodeGlance > Toggle CodeGlance

**Comment by kkinder** [comment]
It might make sense to have some way of auto-toggling it when there's a vertical editor split. It's unlikely, unless you have a huge screen, to want to vertically split code and keep the minimap.

**Comment by thomasmoors** [comment]
There is now, so this could be closed, on mac it is `cmd + shift + G`

**Comment by steinathan** [comment]
On Linux, its `ctrl + shift + G`
