### ISSUE TITLE
Syntax highlighting for injected languages missing in CodeGlance

### ISSUE THREAD

**Issue by rvbdpudar** [Vektah/CodeGlance#153]
I have an Embedded Perl file which contains Javascript code.

I set the template data language to Javascript, and in my main code window both the EP and JS code is syntax highlighted. However, in the CodeGlance sidebar, only the EP code is syntax colored. All of my JS code is not colored.

Screenshots below, both are from the same xxx.js.ep file.

![screen shot 2017-01-30 at 10 23 58 am](https://cloud.githubusercontent.com/assets/23177867/22435761/2d19c35a-e6d6-11e6-9412-729fd66b2797.png)![screen shot 2017-01-30 at 10 24 32 am](https://cloud.githubusercontent.com/assets/23177867/22435762/2d1de0b6-e6d6-11e6-8851-683f3ecb0563.png)

**Comment by Vektah** [comment]
moved to https://github.com/Vektah/CodeGlance/issues/165
