### ISSUE TITLE
I hid the CodeGlance, how can I make it show up?

### ISSUE THREAD

**Issue by heicks** [Vektah/CodeGlance#158]
I hid the CodeGlance, how can I make it show up?

Do you have any shortcut keys?

-------
webstrom 2016.3.3 win7x64

use this: 
step1 & step2  use mouse

![image](https://cloud.githubusercontent.com/assets/12287943/23327119/85997122-fb41-11e6-9513-14a40ab8beb1.png)

**Comment by Vektah** [comment]
You can change the width in settings -> codeglance. 

There is also a show/hide key in the keybinds but it won't do anything if width is set to zero.

I'll set a min width in the next release

**Comment by heicks** [comment]
ty :)
