### ISSUE TITLE
Setting for "render character"

### ISSUE THREAD

**Issue by rogeralsing** [Vektah/CodeGlance#160]
In VS Code minimap, there is a setting to toggle if it should render the actual characters, or just render a line/block instead.

CodeGlance renders characters, giving it a somewhat blurry appearance.
It would be nice to be able to just render the lines/blocks for a cleaner look.

vscode
![vscode](https://cloud.githubusercontent.com/assets/647031/23694956/15cbafb4-03dd-11e7-93d7-120f401d1405.png)

Codeglance
![codeglance](https://cloud.githubusercontent.com/assets/647031/23694962/1962e750-03dd-11e7-9c46-32d346902b08.png)

**Comment by Vektah** [comment]
Wow, that does look super clean, and it would be easy to implement as its already how codeglance works under the hood. It dosen't render characters but instead has an approximate weight for each character. (font rendering to draw 4px is crazy).

To implement this it would actually just be setting the weight to `isWhitespace() ? 0 : 0.8`

**Comment by Vektah** [comment]
Give this a try:
[CodeGlance-1.4.7-blocky.zip](https://github.com/Vektah/CodeGlance/files/827075/CodeGlance-1.4.7-test1.zip)

Feels like its missing something.

**Comment by Vektah** [comment]
![image](https://cloud.githubusercontent.com/assets/2247982/23823014/ea854464-06ac-11e7-9351-715aa251cad9.png)
vs
![image](https://cloud.githubusercontent.com/assets/2247982/23823023/0727f40e-06ad-11e7-8545-451021d67c31.png)

**Comment by Vektah** [comment]
I'm making this the default renderer in 1.5.0

**Comment by rogeralsing** [comment]
Looks beautiful!
