### ISSUE TITLE
How to hide it by default

### ISSUE THREAD

**Issue by vjpr** [Vektah/CodeGlance#163]
I don't want to disable or uninstall the plugin but I want to hide it by default.

Currently it loads enabled by default.

**Comment by Vektah** [comment]
I'm not sure what you mean, ctrl+shift+g will hide/show it. Do you mean you want to turn it on per window?

**Comment by vjpr** [comment]
If I disabled it globally, when I restart IntelliJ, it shows by default.

What I expect is that if I disable it, then re-open my project, it is disabled.

**Comment by Vektah** [comment]
Ahh I see. Yeah that was done deliberately to reduce the number of people disabling it, then creating issues with "Why isn't it working"

https://github.com/Vektah/CodeGlance/commit/a4369f183ac8fd6fddca98553d76a5cabacb386d#diff-a1c58f75c8958ac65408c3de6ceb09edR53

 Maybe I can remove that again now and see...

**Comment by vjpr** [comment]
Thank you that would be great.
