### ISSUE TITLE
Update 1.5.0 doesn't work at all

### ISSUE THREAD

**Issue by TURBODRIVER** [Vektah/CodeGlance#166]
Code doesn't display on the bar at all and scrolling with it doesn't work.
Here's a gif of how it looks: http://i.imgur.com/VXvDJxU.gifv

It happened right after updating and PyCharm restart.

PyCharm Community Edition 2016.3.2
Build #PC-163.10154.50, built on December 28, 2016
JRE: 1.8.0_121-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Trying to disable and enable the plugin didn't help.
Trying to change rendering from Clean to Accurate didn't help.
Trying to uninstall and install again didn't help. It was odd though because the file that was opened after loading PyCharm worked, but closing it and opening it again made it broken.

This happens to every single file, even ones that can't be scrolled.

// I've downloaded the 1.4.6 version from repo which works, thanks for keeping them up.

**Comment by caleb** [comment]
I am also experiencing this on RubyMine 2016.3.2.

It seems to work sometimes but most of the time I get the behavior above.

**Comment by CnlPepper** [comment]
Completely broken for me too. Ubuntu 16.04, pycharm 2013.3.2. Can not switch back to "accurate" renderer... setting is forgotten instantly. Does not render correctly except for first file, on first boot.

**Comment by TURBODRIVER** [comment]
Can confirm as fixed, thanks Vektah!
