### ISSUE TITLE
UI + Settings issues

### ISSUE THREAD

**Issue by Vorror** [Vektah/CodeGlance#170]
I was on an old build(1.4.X). In the new 1.5.1 build scrolling is now "sluggish". When click+dragging using code glance, the preview box trails behind the mouse cursor.

Also the "Render Style" setting doesn't seem to save and reverts on apply/ok.

**Comment by Vektah** [comment]
Can you try doing this?
- Close Intellij
- Go to C:\Users\<User>\\.IntelliJIdeaXX\config\plugins
- delete all the CodeGlance things from here (jars, zips, folders)
- reinstall the plugin from the repo
