### ISSUE TITLE
Transparent background color option

### ISSUE THREAD

**Issue by bradur** [Vektah/CodeGlance#173]
Intellij IDEA 2017.1 has a new feature where you can set a background image for the editor window like this:

* Find Action(Ctrl+Shift+A)
* Search for "Set Background Image")
* Press Enter
* Use the dialog to set image

CodeGlance still displays white background, which is a little jarring:
![test2](https://cloud.githubusercontent.com/assets/1394138/24248009/58c66f3e-0fd6-11e7-891c-407ed0f748e4.png)

Perhaps the background color could be set to transparent so that the background image would be visible from behind?

**Comment by Vektah** [comment]
should be added in 1.5.2

**Comment by shallwefootball** [comment]
i tried to find transparent option in macOS but can't.

Can only in window?
