### ISSUE TITLE
invalid display of long lines

### ISSUE THREAD

**Issue by ildarkhasanshin** [Vektah/CodeGlance#177]
sublime text 3126
![img-2017-03-26-20-49-18](https://cloud.githubusercontent.com/assets/8765305/24332775/c3478b36-1265-11e7-9d3b-0ad2dd6aee03.png)

codeglance 1.5.2 + phpstorm 2017.1
![img-2017-03-26-20-51-55](https://cloud.githubusercontent.com/assets/8765305/24332793/1bf9aef8-1266-11e7-94dc-4e7047bfc988.png)

test file
https://cloud.mail.ru/public/6ntY/nT2pHk7G9

**Comment by Vektah** [comment]
Sorry, Its unlikely this will ever get fixed. I would need to re implement all of the soft line wrapping logic and try to match the editor.
