### ISSUE TITLE
invalid display of too many lines

### ISSUE THREAD

**Issue by hm496** [vektah/CodeGlance#178]
![codeglance_bug](https://cloud.githubusercontent.com/assets/17252784/24337231/5b545b2c-12cd-11e7-903a-3a053ad32a6a.jpg)

codeglance 1.5.2 + WebStorm 2017.1

test file http://vuejs.org/js/vue.js

**Comment by roman4e** [comment]
I confirm that. It disappear after the 4000th line

**Comment by bendem** [comment]
Can confirm, it happens at line when the line 3769 is fully shown on screen.
https://imgur.com/a/nOzQe

**Comment by Jurager** [comment]
Same, after 4258 line scrolls up and not showing the actual position in editor

**Comment by vektah** [comment]
Should be fixed in 1.5.4 by https://github.com/vektah/CodeGlance/pull/203
