### ISSUE TITLE
is transparent option only in Windows?

### ISSUE THREAD

**Issue by shallwefootball** [Vektah/CodeGlance#182]
i tried to find transparent option in macOS but can't.

Can only option in Windows?

**Comment by Vektah** [comment]
Its not transparency to your desktop, its just a background image set in the editor. Pretty sure it should work everywhere, I've used it on both windows and linux. 

You can see the intellij docs [here](https://www.jetbrains.com/help/idea/setting-background-image.html) to set it up.
