### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by jschlieber** [Vektah/CodeGlance#184]
Plugin activated, Editor restarted several times, but no code minimap will be displayed..

CodeGlance Version: 1.5.2
WebStorm 2017.1.2
Build #WS-171.4249.40, built on April 25, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.13.0-37-generic

**Comment by illusive-man** [comment]
Strange. Works great for me (same setup but I'm on Windows).

**Comment by jschlieber** [comment]
It is indeed as it started working again... Closing
