### ISSUE TITLE
"Render Style" setting is not saved

### ISSUE THREAD

**Issue by a1tus** [Vektah/CodeGlance#186]
Hello. I've found that "render style" option settings is not saved.
For example, I select "accurate" variant, press save and exit settings.
Option is applied but if you open settings again then you can see that "clean" option is selected.

PyCharm 2017.1.2 Build #PY-171.4249.47, built on April 26, 2017

**Comment by MuppetGate** [comment]
Yes, seeing the same thing. The **render style** option is not being saved when I close the settings dialog.

**Comment by zartc** [comment]
In fact both '`Render Style`' AND '`Alignment`' options are not saved.
Or more exactly those options are reset to their default value each time the Setting Dialog is opened, even if the CodeGlance panel was not visited by the user.
