### ISSUE TITLE
scroll view not shown in PhpStorm 2017.1.4

### ISSUE THREAD

**Issue by idMolotov** [Vektah/CodeGlance#188]
PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

After update using inner phphstorm update functionality - plugin scroll disappears.

Try to remove it with uninstall, checking in the directories for left files and re-install again gave no result.

**Comment by cronicryo** [comment]
by pressing ctrl + shift +  A on windows and searching code glance. theres a hot key to show visibility. ctrl + shift + G. apparently the setting in settings is labeled "disabled" that hides it and mine was on by default

**Comment by pmirandaarias** [comment]
Mine is ON and I still can't see it.

**Comment by thearabbit** [comment]
I have the same problem, I can't see it on `Webstorm 2017.1.4`.

**Comment by LazzyLizzard** [comment]
Ctrl + Shift + G works for me

**Comment by idMolotov** [comment]
cmd + shift + G (restart may require)

**Comment by TheNaderio** [comment]
On my Mac the Hotkey **cmd + shift + G** opens the search.
With a double press on Shift key you can open the PhpStorm search for functions or everything.
Typing `codeglance` into this bar shows:
![image](https://user-images.githubusercontent.com/25088164/63746182-73881280-c8a4-11e9-8f35-fc3b3a76f0ff.png)

There is a hotkey shown that seems to be doubla assigned, but you can click the result item to toggle CodeGlance.
