### ISSUE TITLE
add UI element to quickly toggle "mini-map"

### ISSUE THREAD

**Issue by bkhouri** [Vektah/CodeGlance#189]
Personally, I don't need the mini-map for all the file-types I modify within IntelliJ.  In addition, for the same filetypes, I may want to display the mini-map for a given file, and have it disabled for another. 

Although the mini-map can be disabled from the settings, it would be nice if you can contribute a quick toggle button, either on the toolbar, or on the tool buttons.  creating a keyboard shortcut would be great too, though not required.

**Comment by Vektah** [comment]
There is already a keyboard shortcut `ctrl + shift + g`. It should be in the visible in the keymap if you want to change it.

![image](https://user-images.githubusercontent.com/2247982/31770695-c9e94ab2-b524-11e7-858f-704e65de077f.png)

PR's are welcome if someone wants to add a button but it would probably need an icon.

**Comment by bkhouri** [comment]
Excellent.. That works.
