### ISSUE TITLE
Can't see CodeGlance

### ISSUE THREAD

**Issue by pmirandaarias** [Vektah/CodeGlance#190]
I have installed, activated, I can't see it. I've removed all the files, installed from the plugin maneger, and/or downloading and install it from the disk, nothing happens. I've updated PhpStorm many times (since 2016), but I never managed to see CodeGlance

![image](https://user-images.githubusercontent.com/20463330/27295912-aa45098c-54ec-11e7-92bb-d2c86dde12a8.png)

Windows 10. phpstorm 32 and 64

**Comment by sinaptik** [comment]
My installation of CodeGlance mysteriously disappeared one day, today I found out that it had disabled itself. You might have the same problem, here's how I fixed mine: In the top-left of your screenshot in the search, enter "codeglance" and click on "CodeGlance" under the "Other Settings" item. Untick "Disabled"

**Comment by pmirandaarias** [comment]
Wonderful. Thanks!!!
