### ISSUE TITLE
CodeGlance does not work in conjunction with Material Theme UI

### ISSUE THREAD

**Issue by reebr** [Vektah/CodeGlance#196]
Hallo,

I've been using the plugin for several months, until I also installed another plugin named [Material Theme UI][1]. And then, CodeGlance stop working.

### steps to reproduce:
- Install Pycharm (or any other Jetbrains IDE).
- Install CodeGlance
- Install Material Theme UI.

> You can install the Material Theme UI before CodeGlance too, has the same effect.

Is there the possibility of performing an improvement to get CodeGlance and Material Theme UI working properly in conjunction?

### CodeGlance settings:
<kbd>![settings][2]</kbd>

### Editor:
<kbd>![main-ui][3]</kbd>

[1]:https://plugins.jetbrains.com/plugin/8006-material-theme-ui
[2]:https://i.imgur.com/rqvtCGb.png
[3]:https://i.imgur.com/PUvZmYo.png

**Comment by VinceBT** [comment]
Uncheck "Disabled" checkbox
