### ISSUE TITLE
Soft-Wrapping file would not change minimap view

### ISSUE THREAD

**Issue by ArtsiomCh** [Vektah/CodeGlance#199]
Soft-Wrap file with long lines would not change minimap. That makes minimap view irrelevant with the actual file view in the editor and made navigation a bit confusing.
PS Not a big deal. But would be nice to have the minimap and editor views completely synchronized.

**Comment by Vektah** [comment]
This plugin works by trying to match the rendering of the pane, but its a cheap approximation. I don't think I will ever add this, but I'm open to a PR that does.
