### ISSUE TITLE
Not working with PyCharm 2017.3.2

### ISSUE THREAD

**Issue by joaonc** [vektah/CodeGlance#200]
Just udpated from PyCharm 2017.2.3 to 2017.3.2 and the CodeGlance plugin is no longer working.

Tried deactivating/reactivating and uninstall/install (with restarts in between) and nothing works.

Later I re-installed PyCharm with JetBrain's JRE, but that didn't change anything.

**More Info**
- This is on a Windows 10 machine.
- A colleague has PyCharm 2017.3.1 on a Mac and the plugin is working fine.

**Comment by JamesMTSloan** [comment]
I am using Windows 7 and the plugin is working with 2017.3.2 (no re-installs or tinkering required) but the highlighted window in the minimap is not correct. It is scrolling such that when the bottom of the highlighted window reaches the bottom of the text in the map, the editor is actually at the bottom of the virtual space under the text (i.e. the last line of text is at the top of the editor). This causes the highlighted window to be misaligned through the file.

Cheers.

**Comment by Izopi4a** [comment]
not showing for me also

phpstorm 2017.3.3 ubuntu gnome

**Comment by dberthia** [comment]
Also not displaying for me in Webstorm 2017.3.3 On Windows 7. tried deactivating, reinstalling, etc.

**Comment by ZuiSong** [comment]
Not Working for me  also . Here is my environment.
```
IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.3007.14, built on January 24, 2018
IntelliJ IDEA EAP User
Expiration date: February 23, 2018
JRE: 1.8.0_152-release-1136-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by mxx-lxg** [comment]
Not showing on macOS 10.12 either.

**Comment by Izopi4a** [comment]
same operation system, same phpstorm version, different computers, on 1 is working on the other it doesn't.

Can we assist somehow so you can somehow see what's the reason it doesnt work ? cuz obviously its random ?

maybe we can clear some cache somewhere ?

**Comment by mxx-lxg** [comment]
I just realised it still works on smaller files.

**Comment by Brunarspunar** [comment]
Suddenly stopped working on ubuntu 16.04 LTS, worked fine before. Resintall of plugin didn't help. 

PyCharm 2017.3.3 (Professional Edition)
Build #PY-173.4301.16, built on January 11, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-116-generic

**Comment by joaonc** [comment]
Ok, now working.  In fact, I think it always worked, except I didn't know how to make it visible.  It probably was hidden during PyCharm's update.

Press `Shift` + `Ctrl` + `G` to toggle visibility!

**Comment by MikeTheWatchGuy** [comment]
Like @Brunarspunar, I too had this checkbox set to disabled.  It seemed to have happened on its own.  I reinstalled several times with no success. Wasn't until I read this Issue that I found the problem was that `disabled` checkbox.

**Comment by theBlbDan** [comment]
Hate to say it, but #metoo on the disabled.  Something, prolly an IntelliJ update, changed it.

**Comment by FairoozRahman** [comment]
It was not working for me, later found out I had to restart the IDE after installing. It works fine now.
