### ISSUE TITLE
Can not drag to scroll.

### ISSUE THREAD

**Issue by YiiGuxing** [vektah/CodeGlance#205]
Version: 1.5.2

![1](https://user-images.githubusercontent.com/10737066/37945001-a7e023ec-31b0-11e8-825e-c4cbb2a3effd.gif)
![2](https://user-images.githubusercontent.com/10737066/37945029-c109d886-31b0-11e8-856d-7207c017aebd.png)

**Comment by vektah** [comment]
Should be fixed in 1.5.4 by https://github.com/vektah/CodeGlance/pull/203
