### ISSUE TITLE
panel doesn't show up in editor

### ISSUE THREAD

**Issue by zbuckley** [vektah/CodeGlance#207]
May just have a setting incorrectly configured. 

Tried reinstalling the plugin as well, but no luck. 

Have it installed but no minimap panel appears in the editor.
I'm using the dark theme, primarily with scala code (not sure if that matters). 

Happy to double check setting keys if anyone has an idea what to check, not certain it's really a bug. Probably me just being confused.

**Comment by vektah** [comment]
Check the settings for codeglance there is a setting to hide it. Ctrl shift g on windows.

**Comment by xushanning** [comment]
thanks

**Comment by g000m** [comment]
cmd-opt+G on Mac OS

**Comment by lhsya** [comment]
Mac OSX 10.11.6 CMD+SHIFT+G

Windows Press CTRL SHIFT A ,

**Comment by nthack** [comment]
> Mac OSX 10.11.6 CMD+SHIFT+G
> 
> Windows Press CTRL SHIFT A ,

Works, thx
