### ISSUE TITLE
Out of commission

### ISSUE THREAD

**Issue by MybeautifulSunShine** [vektah/CodeGlance#222]
This is my version information. I could use it before that. But he can't use it even if I refit it it.
Is it the problem I set up? how My should I do? think you 

IntelliJ IDEA 2018.2.1 (Ultimate Edition)
Build #IU-182.3911.36, built on August 6, 2018
Licensed to lan yu
Subscription is active until May 5, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
![image](https://user-images.githubusercontent.com/31641287/49414448-696e3300-f7ae-11e8-93a9-e2c8318ea19d.png)

**Comment by seiffs** [comment]
> **Ctrl-Shift-G** ? (show/hide) minimap?

I had exactly the same problem. The minimap disappeared (maybe I accidentally pressed the shortcut not knowing about it). I could not find any checkbox in any settings to show/hide the minimap. Only this shortcut mentioned in the issue thread saved me.

**Comment by tonghae** [comment]
Same for me, shortcut brought it back

**Comment by MybeautifulSunShine** [comment]
think
