### ISSUE TITLE
Feature request Xcode like // MARK: something

### ISSUE THREAD

**Issue by patpatpat123** [Vektah/CodeGlance#236]
Hello CodeGlance Team,

First of all, I wanted to say a big thank you for this project.
This is a very helpful.

If I may, I would like to ask for a request which is widely adopted in Xcode, and is very helpful.
In Xcode, if there is a tag: // MARK: Something

![Screen Shot 2019-10-14 at 12 20 02](https://user-images.githubusercontent.com/43899031/66729290-00028a80-ee7d-11e9-905c-d1aa5f5c14d9.png)

The Xcode Code Glance will display it with a different font (much bolder)
Please see the screenshot as well.

This allow from the Code Glance mini map, a faster and clearer way to to just click and get to the lines of code needed.

Thank you so much!

**Comment by markgravity** [comment]
Please, add this feature. It will save my eyes on scrolling

**Comment by tatsuz0u** [comment]
I second that.

**Comment by gcamp806** [comment]
This would definitely be very helpful. I am working on a rewrite of an iOS app into Flutter. This plugin is great as I've become used to a minimap. Having the // MARK: functionality would be so wonderful. It's really a great help in large files, especially once you've become accustomed to using the minimap to quickly locate a section of code.

**Comment by rldaulton** [comment]
Really really really hoping this makes it in this year 🤞

**Comment by Nasller** [comment]
Availavle in last version of CodeGlance Pro

**Comment by patpatpat123** [comment]
Hello @Nasller,

Thank you for your response.
May I know what is the command please?
I tried //MARK (slash slash and the work MARK in uppercase) and no luck.

**Comment by Nasller** [comment]
//MARK: - THIS A COMMENT
try this
color scheme has template

**Comment by patpatpat123** [comment]
Verified, working.
Adopting CodeGlance Pro from now on
Good to close, and big thanks for this three years old request

**Comment by Nasller** [comment]
> Verified, working. Adopting CodeGlance Pro from now on Good to close, and big thanks for this three years old request

Thanks,I am also a user of CodeGlance
