### ISSUE TITLE
Not working in Android Studio 3.6.1

### ISSUE THREAD

**Issue by reynoshsunny** [Vektah/CodeGlance#240]
**Android Studio 3.6.1**
Build #AI-192.7142.36.36.6241897, **built on February 27, 2020**
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8

**Comment by nuhin13** [comment]
Pressing ctrl + shift + g & toggles the CodeGlance plug-in
