### ISSUE TITLE
minimap is not shown anymore :(

### ISSUE THREAD

**Issue by wallride** [Vektah/CodeGlance#244]
I use webstorm 2020.1.1 build#WS-201.7223.93 on windows 10 64bit
Today I found that minimap has been gone, whereas the plugin (v1.5.4) is enabled.

I'm really missing it.

**Comment by damianw345** [comment]
I'm just a user of this plugin and I had same issue. Just make sure it's not disabled (go to settings -> Other Settings -> CodeGlance -> uncheck disabled) ;)

**Comment by NewOrin** [comment]
> I'm just a user of this plugin and I had same issue. Just make sure it's not disabled (go to settings -> Other Settings -> CodeGlance -> uncheck disabled) ;)

thanks bro.
