### ISSUE TITLE
.twig files have no color in the preview

### ISSUE THREAD

**Issue by DrewLandgrave** [Vektah/CodeGlance#36]
When viewing .twig files (using symfony) there is no color in the preview pane. Would be cool if the color was there. Even if it's just the HTML bits

![twig file](https://f.cloud.github.com/assets/2185786/1595755/fc014338-52ef-11e3-8fd4-a4cd272e79e9.jpg)

**Comment by Vektah** [comment]
moved to https://github.com/Vektah/CodeGlance/issues/165
