### ISSUE TITLE
Use editor.paint() instead of coloring text

### ISSUE THREAD

**Issue by vkravets** [Vektah/CodeGlance#51]
Hi 

I noticed that in the CodeGlance we get text of the current editor and 
try to colored it via highlighter, but in this case a lot of internal 
stuff need to implementing by CodeGlance.

After small investigation of the IDEA CE sources and some Swing/AWT 
thing.. I found that any JComponent have ability to take "screenshot" 
from itself. In this case our job only to stretch this image to needed 
size.

We need to make sure that it was ran in the needed thread. E.g.:

``` java
        UIUtil.invokeAndWaitIfNeeded(new Runnable() {
            @Override
            public void run() {
                minimap.update(editor, text, cs, hl, folding);
            }
        });
```

In the minimap.update we can do such things:

``` java
        JComponet component = editor.getContentComponent();
        if (component.getWidth() <= 0 || component.getHeight() <= 0) return;
        Graphics2D g = img.createGraphics();
        g.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_SPEED));

        g.setComposite(CLEAR);
        g.fillRect(0, 0, img.getWidth(), img.getHeight());

        component.paint(g);
        g.dispose();
```

Such code will paint the "image" of the component to the current buffer 
of the minimap.

After we need to scale the image on the GlancePanel in the correct way

Such behavior will avoid to implement some internal stuff of the IDEA 
which perform syntax highlighter, folding etc....

**Comment by Vektah** [comment]
This is a possible solution to moved to https://github.com/Vektah/CodeGlance/issues/165.
