### ISSUE TITLE
Automatically disable CodeGlance for large files

### ISSUE THREAD

**Issue by asdavey** [Vektah/CodeGlance#62]
I have a json resource that is over 100K lines long, and whenever I open that file and forget to have code glance disabled, intellij complains about running out of memory (Xmx - which I have set to 3000MB but that is still not enough).

It would be nice if CodeGlance recognized that the file being opened is considered large by intellij. Intellij apparently lets you configure what size file is considered large - but I can't seem to find that setting. According to the message bar displayed above my file, the default configured limit in 14CE is 2,560,000 - which I assume is bytes.

**Comment by Vektah** [comment]
Fixed in 1.4.3
