### ISSUE TITLE
Scroll performance on OSX

### ISSUE THREAD

**Issue by ingokasch** [Vektah/CodeGlance#67]
After installing the current version 1.4.2 on OSX 10.10.2 the scroll performance, even on small files with a few 100 lines of code, slows down significantly. Scrolling is no longer smooth, instead it skips every other line.

PHPStorm 8.0.2 on a Macbook Pro Retina Mid 2014 with GT 750M

**Comment by ingokasch** [comment]
Update: this is still present on the lastest PHPStorm 10.x version

**Comment by Vektah** [comment]
I have a bad feeling that this is probably going to be related to natural scrolling or retina, both are really difficult to debug without running OSX.

I am going to be doing a general performance pass in the next release so it might go away, but if its every other line then maybe not :-/

**Comment by Vektah** [comment]
might be related to https://github.com/Vektah/CodeGlance/issues/93

**Comment by Vektah** [comment]
Huge overhaul to give pixel perfect scrolling in 1.5.0. Should be fixed
