### ISSUE TITLE
Feature Request: Highlight all found search terms and selected occurrences 

### ISSUE THREAD

**Issue by jamesmehorter** [Vektah/CodeGlance#69]
Hi! Love the plugin! Thanks!

When I search my code for 'foo' and find 8 instances, it would be awesome to see those 8 instances highlighted in the codeglance.

Similar, but separate; also when I select multiple occurrences of 'bar' throughout my code it would be awesome to see all those occurrences highlighted as well (the way it works in Sublime's minimap).

Thanks!

**Comment by RQuadling** [comment]
+1

**Comment by mdziedzic** [comment]
+1

**Comment by Vektah** [comment]
Added in 1.5.0

**Comment by alaaalii** [comment]
@Vektah I was looking for a feature of CodeGlance that highlights all occurrences of the selected code, something like Atom's (minimap-hightlight-selected)[https://atom.io/packages/minimap-highlight-selected]. Is this the same as this feature request? I have CodeGlance 1.5.2 (PyCharm 2017.1.1, masOS 10.12.14) and it currently doesn't do this, it just highlights the selection, not all occurrences.

**Comment by yeazes** [comment]
yeah the same thing here. I cant see that this feature was added

**Comment by rquadling** [comment]
I'm using PHPStorm with CodeGlance 1.5.2. If I search for a phrase and select all occurrences, I can see the blue highlight in the minimap for all the selections.

Seems to work for me.

![image](https://user-images.githubusercontent.com/12801/34589489-eaee2866-f1a8-11e7-9e04-8b5cf466cd9b.png)

**Comment by yeazes** [comment]
yes your right, thats possible, but Atom's minimap-hightlight-selected works differently. There it already highlights all occurrences when selecting only one

**Comment by Sachyyy** [comment]
Would be very helpful if they can deliver this feature.
I have used Visual Studio with a plugin called "RockMargin"
whenever i clicked on a word, it will highlight all occurrences in the right pane as well. it is so easy to navigate.
