### ISSUE TITLE
Renders Twice on Big Monitor

### ISSUE THREAD

**Issue by gschier** [Vektah/CodeGlance#70]
My resolution is 2560 x 1440, and at this size, CodeGlance seems to render twice. ![bug](https://cloud.githubusercontent.com/assets/587576/6720829/2eb6b42e-cd84-11e4-884e-500204af860b.png)

**Comment by KaelWD** [comment]
Confirmed on Windows 10 as well (1920x1080 monitor in portrait mode).

**Comment by Vektah** [comment]
Fixed in 1.5.0

**Comment by gschier** [comment]
Woo, thanks!
