### ISSUE TITLE
Feature: CodeGlance should paint with the same colors as configured in Colors And Fonts

### ISSUE THREAD

**Issue by semicontinuity** [Vektah/CodeGlance#73]
For instance, I have configured brown color for Enums, but they are displayed in black

**Comment by Vektah** [comment]
Its a problem with the way intellij parse files. The lowest level - the one that I can grab for the current file - only has the tokens.

There is a second pass done later to generate the PSI tree and this is where a lot of additional color comes from. You can see this happen sometimes when the file will load without color and then as it recognizes methods and types it gives them colors. 

Sadly accessing this second level is much harder. Probably not going to be fixed I'm afraid.
