### ISSUE TITLE
Extension ejs has no color in minimap

### ISSUE THREAD

**Issue by warlock00** [Vektah/CodeGlance#76]
Extension ejs for a html file with embedded js; fails to show color in minimap.
If I change extension to htm it is fine.

**Comment by Vektah** [comment]
Its a problem with the way intellij parse files. The lowest level - the one that I can grab for the current file - only has the tokens.

There is a second pass done later to generate the PSI tree and this is where a lot of additional color comes from. You can see this happen sometimes when the file will load without color and then as it recognizes methods and types it gives them colors. 

Sadly accessing this second level is much harder. Probably not going to be fixed I'm afraid.
