### ISSUE TITLE
JAR file cannot be downloaded

### ISSUE THREAD

**Issue by mischkl** [Vektah/CodeGlance#81]
When attempting to download the JAR, whether from the JetBrains plugin page or from the link on GitHub, only an empty response is returned for http://public.vektah.net/codeglance/net/vektah/CodeGlance/1.4.2/CodeGlance-1.4.2.jar

This applies only to version 1.4.2; 1.4.1 still works fine.

**Comment by Vektah** [comment]
Thats very odd, it works fine here. Could there be a firewall doing some spooky stuff on your end?
