### ISSUE TITLE
Plugin does nothing at all for me

### ISSUE THREAD

**Issue by MightyPork** [Vektah/CodeGlance#86]
It worked before - a few months ago. I'm not sure if something in my settings broke it or what, but reinstalling doesn't help.

The preview column next to the editor is simply not there at all. I tried looking for a resize handle in case it had zero width, but it is simply gone.

I tried in PhpStorm 9.0 and 8.0.3, same result - nothing.

Attaching a log file.

[idea.log](https://gist.github.com/MightyPork/6f8baf112c57894fe36c)

**Comment by Vektah** [comment]
Check in the settings under CodeGlance, make sure that 'disabled' is unchecked and that there is a value in the width box.

Might also be related to https://github.com/Vektah/CodeGlance/issues/98

**Comment by MightyPork** [comment]
Okay yes it was disabled, I didn't even know there was a settings page for the plugin.

But why is "disabled" even a thing, and why was it checked by default? weird.

**Comment by Vektah** [comment]
I'm not sure, its certainly not supposed to be disabled by default. It was a requested feature - its nice to be able to disable it if you are doing lots of vertical splits.

There is also a shortcut to toggle it, ctrl+shift+G. Maybe its close to another shortcut you use?

**Comment by Vektah** [comment]
To avoid this pain in the future I'm going to reset disabled on startup.

**Comment by MightyPork** [comment]
I'm not sure that's a good idea (if someone wants to keep it disabled), maybe it'd suffice to just mention it to the plugin description.

It seems the config file stays when you uninstall it, so maybe something changed between versions and it got messed up. Working OK now.

**Comment by Vektah** [comment]
It seems reasonable to me, if someone wants to totally disable the plugin they can do it from the plugin interface. 

Disable probably should have been called 'Hide'.

Given #98 and related issues resetting disabled on boot would cause less headaches than relying on people reading docs.
