### ISSUE TITLE
Doesn't work with CLion 1.1

### ISSUE THREAD

**Issue by Eloff** [Vektah/CodeGlance#89]
It worked with 1.05, but with 1.1 once you install and restart CLion it's not installed. It's not in the list of plugins, enabled, disabled, or otherwise.

There's probably a log somewhere with relevant information, please let me know where to look so I can attach the info.

**Comment by Vektah** [comment]
Might be related to https://github.com/Vektah/CodeGlance/issues/98

Could you try the fix @misdake suggests?
