### ISSUE TITLE
CodeGlance gets confused by natural scrolling on OS X

### ISSUE THREAD

**Issue by chrisvest** [Vektah/CodeGlance#93]
Using a track pad with natural and smooth scrolling on OS X scrolls in the opposite direction of "normal" scrolling, in that it provides the illusion that you are moving the content rather than the scroll bar cursor.

When you scroll over the CodeGlance view, the scroll behaviour is largely kept the same as if you had been scrolling over the main code panel, but the CodeGlance view is somewhat erratic and occasionally jumps back a step near the start and end of a scroll. It is certainly not as smooth as scrolling in the code panel.

**Comment by Vektah** [comment]
I'm going to close this as wontfix as I dont have any OSX devices to test on. I'm open to a PR though.

The code that handles the scroll wheel is here https://github.com/Vektah/CodeGlance/blob/master/src/main/java/net/vektah/codeglance/Scrollbar.kt#L108
