### ISSUE TITLE
[Feature Request] Set minimap at the left side of the editor

### ISSUE THREAD

**Issue by ikrsh** [Vektah/CodeGlance#95]
Optional setting to set the mini map at the left side of the editor along with line numbers, just like in Atom text editor.
In other words, change position of mini map from right side to left side or from left side to right side of the editor.

![screenshot from 2015-10-07 18 50 58](https://cloud.githubusercontent.com/assets/9942725/10338575/6f4b68fa-6d24-11e5-947a-fd94b653bf7e.png)

**Comment by Vektah** [comment]
Will have a config option in 1.5.0
