### ISSUE TITLE
Toggle minimap visibility shortcut

### ISSUE THREAD

**Issue by LouisCAD** [Vektah/CodeGlance#96]
Hi!

This plugin is very helpful, but sometimes, I need more space to see long lines of code, especially when I'm using split view. Could you add the ability to set a shortcut to show/hide the minimap quickly, without having to browse the settings each time?

Thanks, and all the best!

Louis CAD

**Comment by mdwhatcott** [comment]
+1 (great plugin BTW)

**Comment by Vektah** [comment]
Ctrl+Shift+G, configurable in the keymappings
