### ISSUE TITLE
Out Of Memory popup triggered on long classes

### ISSUE THREAD

**Issue by LouisCAD** [Vektah/CodeGlance#97]
Hi!

I'm a minimap lover (and a CodeGlance lover by extension), but today, when I took a look at a very very long class (RecyclerView in Android Support Library), after some scrolling, the minimap displayed, and immediately, I got the Out Of Memory popup, with the RAM bar at ~230MB/2024MB. You san see the screenshot below:

![screen shot 2015-10-29 at 23 33 03](https://cloud.githubusercontent.com/assets/6975237/10834127/270172a4-7e97-11e5-8dd0-28f3aca6a55b.png)

Each time I dismiss the popup by not clicking Shutdown, and I scroll for a few lines, it appears again. The only way to get rid of this temporarily is to forget the idea of watching the large file, and if you still want to watch/edit the large file, you have to disable completely the plugin... :disappointed: 

Note that I tested on Android Studio 1.4 stable channel and got the same results, so it's not related to the alpha version of Android Studio.

I hope it can be fixed, or it can automatically disable itself on large files to prevent this annoying bug.

All the best!

**Comment by Vektah** [comment]
This should be a lot better in 1.4.3, if you are still having issues feel free to reopen.

**Comment by LouisCAD** [comment]
Thank you very much! Enabling it again :)

**Comment by woyaowenzi** [comment]
I met the same problem in Android Studio 2.1.
