### ISSUE TITLE
Update to 15?

### ISSUE THREAD

**Issue by daarond** [Vektah/CodeGlance#98]
I've really enjoyed minimap. Any hopes of getting this updated to Intellij 15?

**Comment by kcwill2** [comment]
Love this plugin. Would love to see an update as well.

**Comment by vkravets** [comment]
Updated to 15 without any problems, working well!

**Comment by mdsina** [comment]
Not working in PhpStorm and Idea

**Comment by misdake** [comment]
Updated IDEA to 15.0.2 EAP and didn't see CodeGlance.
I checked CodeGlance.xml in .IdeaIC15/config/options and found that an item named "disabled" is "true". set it "false", restarted IDE and got CodeGlance back :D

**Comment by Vektah** [comment]
Intellij 15 should already be supported, you may need to reinstall it after updating.
